name: flutter_training
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  dio: 5.1.2
  json_serializable: ^6.7.0
  hooks_riverpod: ^2.3.4
  flutter_native_splash: ^2.3.4
  flutter_chat_ui: ^1.6.9
  riverpod_generator: ^2.3.5
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  http: ^1.1.0
  mime: ^1.0.4
  uuid: ^4.1.0
  flutter_hooks: ^0.20.3
  flutter_chat_types: ^3.6.2
  riverpod_annotation: ^2.3.0
  auto_size_text: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_geochat.png"

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/mock/json/messages.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages