name: Test Field

#on: issue_comment
on: issue_comment

jobs:
  build:
    runs-on: [ self-hosted, macOS ] # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v3
      - name: Show MacOS version
        run: sw_vers

      - name: Get Pull Request Comments
        id: comments
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          JSON_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments") # Get Body From Github API
          BODY_VALUE=$(echo "$JSON_DATA" | jq -r '.[-1].body')

          RELEASE_NOTE=$(echo $BODY_VALUE|grep 'RELEASE_NOTE_ACTIONS : '| sed -n 's/.*RELEASE_NOTE_ACTIONS : \[\(.*\)\].*/\1/p')
          export RELEASE_NOTE
          echo "$RELEASE_NOTE"

      - name: release trigger
        run: |
          if [ -n "$RELEASE_NOTE" ]; then
            echo "$RELEASE_NOTE"
          else
            echo "THIS IS NOT RELEASE NOTE"
          fi