name: Test Field

#on: issue_comment
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: [ self-hosted, macOS ] # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v3
      - name: Show MacOS version
        run: sw_vers

      - name: Get Pull Request Comments
        id: comments
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          JSON_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments") # Get Body From Github API
          BODY_VALUE=$(echo "$JSON_DATA" | jq -r '.[].body')
          echo "LAST COMMENT : $BODY_VALUE"

      - name: Display Pull Request Comments
        run: |
          echo "Pull Request Comments: ${{ steps.comments.outputs.comments }}"
